package InterviewProblems.Sorting.FindTheDifference;

import static java.util.Arrays.sort;

public class FindTheDifference {

    // Let n = the length of the string s.
    //
    // Time: O(n log n)
    // --> O(n log n) for sorting the array
    // --> O(1) for finding the difference at the end of the t array.
    // Space: O(n)
    // --> O(n) to create char arrays of the strings s and t.
    // --> O(1) or O(n) depending on the sorting algorithm

    public static void main(String[] args) {
        FindTheDifference findTheDifference = new FindTheDifference();

        // Input: s = "", t = "y"
        // Output: "y"
        char extraLetter = findTheDifference.findTheDifference("", "y");
        System.out.println(extraLetter);  // y

        // Input: s = "abcd", t = "abcde"
        // Output: "e"
        // Explanation: 'e' is the letter that was added.
        char extraLetter2 = findTheDifference.findTheDifference("abcd", "abcde");
        System.out.println(extraLetter2);  // e

        // Input: s = "t", t = "tt"
        // Output: "t"
        // Explanation: 't' is the letter that was added.
        char extraLetter3 = findTheDifference.findTheDifference("t", "tt");
        System.out.println(extraLetter3);  // t

        // Input: s = "cba", t = "abcd"
        // Output: "d"
        // Explanation: 'd' is the letter that was added.
        char extraLetter4 = findTheDifference.findTheDifference("cba", "abcd");
        System.out.println(extraLetter4);  // d

        // Input: s = "bcd", t = "abcd"
        // Output: "a"
        // Explanation: 'a' is the letter that was added.
        char extraLetter5 = findTheDifference.findTheDifference("bcd", "abcd");
        System.out.println(extraLetter5);  // a
    }

    /**
     * You are given two strings s and t.
     *
     * String t is generated by random shuffling string s and then add one more
     * letter at a random position.
     *
     * Return the letter that was added to t.
     *
     * Preconditions:
     * - 0 <= s.length <= 1000
     * - t.length == s.length + 1
     * - s and t consist of lowercase English letters.
     */
    public char findTheDifference(String s, String t) {
        // convert strings to char arrays
        char[] sArray = s.toCharArray();
        char[] tArray = t.toCharArray();

        // sort the arrays
        sort(sArray);
        sort(tArray);

        // find the difference
        int sIndex = 0;
        int tIndex = 0;
        while (sIndex < sArray.length && tIndex < tArray.length) {
            if (sArray[sIndex] != tArray[tIndex]) {
                return tArray[tIndex];
            }
            sIndex++;
            tIndex++;
        }
        return tArray[tArray.length - 1];
    }
}
