package InterviewProblems.Hashmaps.FindTheDifference;

import java.util.HashMap;
import java.util.Map;

public class FindTheDifference {

    // Let n = the length of the string s.
    //
    // Time: O(n)
    // --> O(n) to populate the character counts of string s and t.
    // --> O(n) to find the extra character in t.
    // Space: O(n)
    // --> O(n) to store the character counts of string s and t.

    public static void main(String[] args) {
        FindTheDifference findTheDifference = new FindTheDifference();

        // Input: s = "", t = "y"
        // Output: "y"
        char extraLetter = findTheDifference.findTheDifference("", "y");
        System.out.println(extraLetter);  // y

        // Input: s = "abcd", t = "abcde"
        // Output: "e"
        // Explanation: 'e' is the letter that was added.
        char extraLetter2 = findTheDifference.findTheDifference("abcd", "abcde");
        System.out.println(extraLetter2);  // e

        // Input: s = "t", t = "tt"
        // Output: "t"
        // Explanation: 't' is the letter that was added.
        char extraLetter3 = findTheDifference.findTheDifference("t", "tt");
        System.out.println(extraLetter3);  // t

        // Input: s = "cba", t = "abcd"
        // Output: "d"
        // Explanation: 'd' is the letter that was added.
        char extraLetter4 = findTheDifference.findTheDifference("cba", "abcd");
        System.out.println(extraLetter4);  // d

        // Input: s = "bcd", t = "abcd"
        // Output: "a"
        // Explanation: 'a' is the letter that was added.
        char extraLetter5 = findTheDifference.findTheDifference("bcd", "abcd");
        System.out.println(extraLetter5);  // a
    }

    /**
     * You are given two strings s and t.
     *
     * String t is generated by random shuffling string s and then add one more
     * letter at a random position.
     *
     * Return the letter that was added to t.
     *
     * Preconditions:
     * - 0 <= s.length <= 1000
     * - t.length == s.length + 1
     * - s and t consist of lowercase English letters.
     */
    public char findTheDifference(String s, String t) {
        Map<Character, Integer> lettersInS = countLetters(s);
        Map<Character, Integer> lettersInT = countLetters(t);
        return findExtraLetter(lettersInS, lettersInT);
    }

    private Map<Character, Integer> countLetters(String s) {
        Map<Character, Integer> letters = new HashMap<>();
        for (char c : s.toCharArray()) {
            if (!letters.containsKey(c)) {
                letters.put(c, 0);
            }
            letters.put(c, letters.get(c) + 1);
        }
        return letters;
    }

    private char findExtraLetter(Map<Character, Integer> lettersInS,
                                 Map<Character, Integer> lettersInT) {
        for (char c : lettersInT.keySet()) {
            // if counts are different, then c is the extra letter
            if (lettersInS.get(c) != lettersInT.get(c)) {
                return c;
            }
        }
        return ' ';  // impossible
    }
}
