package InterviewProblems.BitManipulation.FindTheDifference;

public class FindTheDifference {

    // Let n = the length of the string s.
    //
    // Time: O(n)
    // --> We must traverse the string t once.
    // Space: O(1)
    // --> We only store one variable, extraLetter.

    public static void main(String[] args) {
        FindTheDifference findTheDifference = new FindTheDifference();

        // Input: s = "", t = "y"
        // Output: "y"
        char extraLetter = findTheDifference.findTheDifference("", "y");
        System.out.println(extraLetter);  // y

        // Input: s = "abcd", t = "abcde"
        // Output: "e"
        // Explanation: 'e' is the letter that was added.
        char extraLetter2 = findTheDifference.findTheDifference("abcd", "abcde");
        System.out.println(extraLetter2);  // e

        // Input: s = "t", t = "tt"
        // Output: "t"
        // Explanation: 't' is the letter that was added.
        char extraLetter3 = findTheDifference.findTheDifference("t", "tt");
        System.out.println(extraLetter3);  // t

        // Input: s = "cba", t = "abcd"
        // Output: "d"
        // Explanation: 'd' is the letter that was added.
        char extraLetter4 = findTheDifference.findTheDifference("cba", "abcd");
        System.out.println(extraLetter4);  // d

        // Input: s = "bcd", t = "abcd"
        // Output: "a"
        // Explanation: 'a' is the letter that was added.
        char extraLetter5 = findTheDifference.findTheDifference("bcd", "abcd");
        System.out.println(extraLetter5);  // a
    }

    /**
     * You are given two strings s and t.
     *
     * String t is generated by random shuffling string s and then add one more
     * letter at a random position.
     *
     * Return the letter that was added to t.
     *
     * Preconditions:
     * - 0 <= s.length <= 1000
     * - t.length == s.length + 1
     * - s and t consist of lowercase English letters.
     */
    public char findTheDifference(String s, String t) {
        char extraLetter = 0;
        for (char sCharacter : s.toCharArray()) {
            extraLetter ^= sCharacter;
        }

        for (char tCharacter : t.toCharArray()) {
            extraLetter ^= tCharacter;
        }

        return extraLetter;
    }
}
